pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('SCM Checkout') {
            steps {
                git credentialsId: 'GitHub', url: 'https://github.com/abhi-gadge1773/java-app.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'ls -la'
                sh 'cd my-app1 && mvn clean package'
                // If your project is in root, just use: sh 'mvn clean package'
            }
        }

        stage('Docker Build Image') {
            steps {
                sh 'ls -la'
                sh 'docker build -t abhi2404/javaapp my-app1'
                // If the Dockerfile is in root: sh 'docker build -t abhi2404/javaapp .'
            }
        }

        stage('Docker Push Image') {
            steps {
                withCredentials([string(credentialsId: 'DOCKER_HUB_PASSWD', variable: 'DOCKER_HUB_PASSWD_CODE')]) {
                    sh "docker login -u abhi2404 -p ${DOCKER_HUB_PASSWD_CODE}"
                    sh 'docker push abhi2404/javaapp'
                }
            }
        }
    }
}
